# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

import inspect

import nv_dfm_core.exec
import nv_dfm_core.exec.discovery
import nv_dfm_core.telemetry
from nv_dfm_core.exec import FsspecConfig, SecretsVaultConfig
import testpkg.lib.adapters.compute_adapter
import testpkg.lib.adapters.controller_adapter
import testpkg.lib.adapters.process_adapter
import testpkg.lib.adapters.report_adapter


class ThisSite(nv_dfm_core.exec.Site):
    def __init__(self, dfm_context: nv_dfm_core.exec.DfmContext):
        super().__init__(
            dfm_context=dfm_context,
            cache_config=FsspecConfig(protocol='file', storage_options={}, base_path=None),
            secrets_vault_config=SecretsVaultConfig(path=None, args={})
        )
        # providers
        # adapters
        _adapter_params = inspect.signature(testpkg.lib.adapters.process_adapter.ProcessAdapter).parameters
        _adapter_kwargs = {}
        if 'site' in _adapter_params:
            _adapter_kwargs['site'] = self
        if 'provider' in _adapter_params:
            _adapter_kwargs['provider'] = None
        self.adapter_testpkg_lib_adapters_process_adapter_ProcessAdapter = testpkg.lib.adapters.process_adapter.ProcessAdapter(**_adapter_kwargs)
        _adapter_params = inspect.signature(testpkg.lib.adapters.compute_adapter.ComputeAdapter).parameters
        _adapter_kwargs = {}
        if 'site' in _adapter_params:
            _adapter_kwargs['site'] = self
        if 'provider' in _adapter_params:
            _adapter_kwargs['provider'] = None
        self.adapter_testpkg_lib_adapters_compute_adapter_ComputeAdapter = testpkg.lib.adapters.compute_adapter.ComputeAdapter(**_adapter_kwargs)
        _adapter_params = inspect.signature(testpkg.lib.adapters.controller_adapter.ControllerAdapter).parameters
        _adapter_kwargs = {}
        if 'site' in _adapter_params:
            _adapter_kwargs['site'] = self
        if 'provider' in _adapter_params:
            _adapter_kwargs['provider'] = None
        self.adapter_testpkg_lib_adapters_controller_adapter_ControllerAdapter = testpkg.lib.adapters.controller_adapter.ControllerAdapter(**_adapter_kwargs)
        _adapter_params = inspect.signature(testpkg.lib.adapters.report_adapter.ReportAdapter).parameters
        _adapter_kwargs = {}
        if 'site' in _adapter_params:
            _adapter_kwargs['site'] = self
        if 'provider' in _adapter_params:
            _adapter_kwargs['provider'] = None
        self.adapter_testpkg_lib_adapters_report_adapter_ReportAdapter = testpkg.lib.adapters.report_adapter.ReportAdapter(**_adapter_kwargs)
    
    async def call_tasks_ProcessData(self, **kwargs):
        # prepare arguments
        input_state = kwargs.get("input_state", None)
        interval = kwargs.get("interval", None)
        timestamp = kwargs.get("timestamp", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "input_state": input_state,
           "interval": interval,
           "timestamp": timestamp,
        }
        # call adapter with telemetry
        with nv_dfm_core.telemetry.adapter_span(self.dfm_context, "ProcessAdapter", "tasks.ProcessData") as _dfm_span_:
            _dfm_result_ = await self.adapter_testpkg_lib_adapters_process_adapter_ProcessAdapter.body(**_dfm_prepped_kwargs_)
            if _dfm_span_:
                _dfm_span_.set_ok()
            return _dfm_result_

    async def discover_tasks_ProcessData(self, **kwargs):
        # prepare arguments
        input_state = kwargs.get("input_state", None)
        interval = kwargs.get("interval", None)
        timestamp = kwargs.get("timestamp", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "input_state": input_state,
           "interval": interval,
           "timestamp": timestamp,
        }
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(adapter=self.adapter_testpkg_lib_adapters_process_adapter_ProcessAdapter, **_dfm_prepped_kwargs_)

    async def call_tasks_RunComputation(self, **kwargs):
        # prepare arguments
        initial_state = kwargs.get("initial_state", None)
        input_state = kwargs.get("input_state", None)
        rate_alpha = kwargs.get("rate_alpha", None)
        rate_beta = kwargs.get("rate_beta", None)
        step_size = kwargs.get("step_size", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "initial_state": initial_state,
           "input_state": input_state,
           "rate_alpha": rate_alpha,
           "rate_beta": rate_beta,
           "step_size": step_size,
        }
        # call adapter with telemetry
        with nv_dfm_core.telemetry.adapter_span(self.dfm_context, "ComputeAdapter", "tasks.RunComputation") as _dfm_span_:
            _dfm_result_ = await self.adapter_testpkg_lib_adapters_compute_adapter_ComputeAdapter.body(**_dfm_prepped_kwargs_)
            if _dfm_span_:
                _dfm_span_.set_ok()
            return _dfm_result_

    async def discover_tasks_RunComputation(self, **kwargs):
        # prepare arguments
        initial_state = kwargs.get("initial_state", None)
        input_state = kwargs.get("input_state", None)
        rate_alpha = kwargs.get("rate_alpha", None)
        rate_beta = kwargs.get("rate_beta", None)
        step_size = kwargs.get("step_size", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "initial_state": initial_state,
           "input_state": input_state,
           "rate_alpha": rate_alpha,
           "rate_beta": rate_beta,
           "step_size": step_size,
        }
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(adapter=self.adapter_testpkg_lib_adapters_compute_adapter_ComputeAdapter, **_dfm_prepped_kwargs_)

    async def call_tasks_RunController(self, **kwargs):
        # prepare arguments
        input_state = kwargs.get("input_state", None)
        results = kwargs.get("results", None)
        rate_alpha = kwargs.get("rate_alpha", None)
        adjusted_rate = kwargs.get("adjusted_rate", None)
        step_size = kwargs.get("step_size", None)
        mode = kwargs.get("mode", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "input_state": input_state,
           "results": results,
           "rate_alpha": rate_alpha,
           "adjusted_rate": adjusted_rate,
           "step_size": step_size,
           "mode": mode,
        }
        # call adapter with telemetry
        with nv_dfm_core.telemetry.adapter_span(self.dfm_context, "ControllerAdapter", "tasks.RunController") as _dfm_span_:
            _dfm_result_ = await self.adapter_testpkg_lib_adapters_controller_adapter_ControllerAdapter.body(**_dfm_prepped_kwargs_)
            if _dfm_span_:
                _dfm_span_.set_ok()
            return _dfm_result_

    async def discover_tasks_RunController(self, **kwargs):
        # prepare arguments
        input_state = kwargs.get("input_state", None)
        results = kwargs.get("results", None)
        rate_alpha = kwargs.get("rate_alpha", None)
        adjusted_rate = kwargs.get("adjusted_rate", None)
        step_size = kwargs.get("step_size", None)
        mode = kwargs.get("mode", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "input_state": input_state,
           "results": results,
           "rate_alpha": rate_alpha,
           "adjusted_rate": adjusted_rate,
           "step_size": step_size,
           "mode": mode,
        }
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(adapter=self.adapter_testpkg_lib_adapters_controller_adapter_ControllerAdapter, **_dfm_prepped_kwargs_)

    async def call_tasks_GenerateReport(self, **kwargs):
        # prepare arguments
        results = kwargs.get("results", None)
        rate_alpha = kwargs.get("rate_alpha", None)
        rate_beta = kwargs.get("rate_beta", None)
        include_details = kwargs.get("include_details", None)
        include_summary = kwargs.get("include_summary", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "results": results,
           "rate_alpha": rate_alpha,
           "rate_beta": rate_beta,
           "include_details": include_details,
           "include_summary": include_summary,
        }
        # call adapter with telemetry
        with nv_dfm_core.telemetry.adapter_span(self.dfm_context, "ReportAdapter", "tasks.GenerateReport") as _dfm_span_:
            _dfm_result_ = await self.adapter_testpkg_lib_adapters_report_adapter_ReportAdapter.body(**_dfm_prepped_kwargs_)
            if _dfm_span_:
                _dfm_span_.set_ok()
            return _dfm_result_

    async def discover_tasks_GenerateReport(self, **kwargs):
        # prepare arguments
        results = kwargs.get("results", None)
        rate_alpha = kwargs.get("rate_alpha", None)
        rate_beta = kwargs.get("rate_beta", None)
        include_details = kwargs.get("include_details", None)
        include_summary = kwargs.get("include_summary", None)
        # handle exposed args (if any)
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "results": results,
           "rate_alpha": rate_alpha,
           "rate_beta": rate_beta,
           "include_details": include_details,
           "include_summary": include_summary,
        }
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(adapter=self.adapter_testpkg_lib_adapters_report_adapter_ReportAdapter, **_dfm_prepped_kwargs_)

    