# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Any, Dict, Literal, Union

from nv_dfm_core.api import Advise, NodeParam, Operation, PlaceParam
from testpkg.fed.schema.tasks import InputState
from testpkg.lib.custom_types import CustomModel


class ProcessData(Operation):
    """
    Process the input data

    Parameters:
        input_state: [Accepts: literal input, node input, place input. Discoverable]
        interval: [Accepts: literal input, node input, place input. Discoverable]
            The time interval
        timestamp: [Accepts: literal input, node input, place input. Discoverable]
            The timestamp

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['testpkg.fed.api.tasks.ProcessData'] = (
        'testpkg.fed.api.tasks.ProcessData'
    )
    __api_name__: Literal['tasks.ProcessData'] = 'tasks.ProcessData'
    input_state: Union[InputState, NodeParam, PlaceParam, Advise]
    interval: Union[float, bool, CustomModel, NodeParam, PlaceParam, Advise]
    timestamp: Union[CustomModel, NodeParam, PlaceParam, Advise]


class RunComputation(Operation):
    """
    Run the computation

    Parameters:
        initial_state: [Accepts: literal input, node input, place input. Discoverable]
            The initial state
        input_state: [Accepts: literal input, node input, place input. Discoverable]
            The input state
        rate_alpha: [Accepts: literal input, node input, place input. Discoverable]
            The alpha rate
        rate_beta: [Accepts: literal input, node input, place input. Discoverable]
            The beta rate
        step_size: [Accepts: literal input, node input, place input. Discoverable]
            The step size

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['testpkg.fed.api.tasks.RunComputation'] = (
        'testpkg.fed.api.tasks.RunComputation'
    )
    __api_name__: Literal['tasks.RunComputation'] = 'tasks.RunComputation'
    initial_state: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    input_state: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    rate_alpha: Union[float, NodeParam, PlaceParam, Advise]
    rate_beta: Union[float, NodeParam, PlaceParam, Advise]
    step_size: Union[float, NodeParam, PlaceParam, Advise]


class RunController(Operation):
    """
    Run the controller

    Parameters:
        input_state: [Accepts: literal input, node input, place input. Discoverable]
            The input state
        results: [Accepts: literal input, node input, place input. Discoverable]
            The computation results
        rate_alpha: [Accepts: literal input, node input, place input. Discoverable]
            The alpha rate
        adjusted_rate: [Accepts: literal input, node input, place input. Discoverable]
            The adjusted rate
        step_size: [Accepts: literal input, node input, place input. Discoverable]
            The step size
        mode: [Accepts: literal input, node input, place input. Discoverable]
            The operating mode

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['testpkg.fed.api.tasks.RunController'] = (
        'testpkg.fed.api.tasks.RunController'
    )
    __api_name__: Literal['tasks.RunController'] = 'tasks.RunController'
    input_state: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    results: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    rate_alpha: Union[float, NodeParam, PlaceParam, Advise]
    adjusted_rate: Union[float, NodeParam, PlaceParam, Advise]
    step_size: Union[float, NodeParam, PlaceParam, Advise]
    mode: Union[str, NodeParam, PlaceParam, Advise]


class GenerateReport(Operation):
    """
    Generate a report

    Parameters:
        results: [Accepts: literal input, node input, place input. Discoverable]
            The results
        rate_alpha: [Accepts: literal input, node input, place input. Discoverable]
            The alpha rate
        rate_beta: [Accepts: literal input, node input, place input. Discoverable]
            The beta rate
        include_details: [Accepts: literal input, node input, place input. Discoverable]
            Whether to include details
        include_summary: [Accepts: literal input, node input, place input. Discoverable]
            Whether to include summary

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['testpkg.fed.api.tasks.GenerateReport'] = (
        'testpkg.fed.api.tasks.GenerateReport'
    )
    __api_name__: Literal['tasks.GenerateReport'] = 'tasks.GenerateReport'
    results: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    rate_alpha: Union[float, NodeParam, PlaceParam, Advise]
    rate_beta: Union[float, NodeParam, PlaceParam, Advise]
    include_details: Union[bool, NodeParam, PlaceParam, Advise]
    include_summary: Union[bool, NodeParam, PlaceParam, Advise]
