# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-MODGEN. DO NOT MODIFY.
"""


from typing import Any
from dataclasses import dataclass, field

from nv_dfm_core.api import ErrorToken, StopToken
from nv_dfm_core.exec import (
    Activation,
    activate_when_places_ready,
    ControlPlace,
    CountingPlace,
    DfmContext,
    Frame,
    FlowInfo,
    Net,
    PanicError,
    Place,
    QueuePlace,
    tagged_json_value_to_object,
    TransitionTryActivateFunc,
)
from examplefed.fed.runtime.reception import ThisSite

@dataclass
class ThisNet(Net):
    """Net for pipeline "test" at site somesite"""

    # Places
    # Transition t1
    __start_place__: Place = field(default_factory=lambda: ControlPlace(name='__start_place__', is_loop_head=False))
    p1: Place = field(default_factory=lambda: QueuePlace(name='p1', is_sticky=False))
    p2: Place = field(default_factory=lambda: QueuePlace(name='p2', is_sticky=False))

    def get_activation_functions(self) -> list[TransitionTryActivateFunc]:
        return [
            self.t1_try_activate,
        ]

    # Transition t1
    def t1_try_activate(self) -> list[Activation]:
        return activate_when_places_ready(
            self.t1_fire,
            self.t1_signal_error,
            self.t1_signal_stop,
            self.__start_place__,
            self.p1,
            self.p2,
        )

    async def t1_signal_error(self, _site_: ThisSite, _dfm_context_: DfmContext, _frame_: Frame, _error_: ErrorToken) -> None:
        await _dfm_context_.send_to_place(to_job=None, to_site='somesite', to_place='p2', frame=_frame_, is_yield=False, data=_error_, node_id=None)

    async def t1_signal_stop(self, _site_: ThisSite, _dfm_context_: DfmContext, _frame_: Frame, _data_: dict[str, Any]) -> None:
        pass

    async def t1_fire(self, _site_: ThisSite, _dfm_context_: DfmContext, _frame_: Frame, _data_: dict[str, Any]) -> None:
        x = await _site_.call_op1()
        await _dfm_context_.send_to_place(to_job=None, to_site='somesite', to_place='p2', frame=_frame_, is_yield=False, data=x, node_id=None)
