# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

import inspect

import nv_dfm_core.exec
import nv_dfm_core.exec.discovery
from nv_dfm_core.exec import FsspecConfig, SecretsVaultConfig

from tests.assets.testfed.lib.op_impls import (
    BinaryOpImpl,
    NullaryOpImpl,
    NullaryOpTupleImpl,
    UnaryOpImpl,
)


class provider1(nv_dfm_core.exec.Provider):
    def __init__(self, site: nv_dfm_core.exec.Site):
        super().__init__(site=site)
        self.adapter_testfed_lib_op_impls_NullaryOpImpl = NullaryOpImpl()
        self.adapter_testfed_lib_op_impls_NullaryOpTupleImpl = NullaryOpTupleImpl()
        self.adapter_testfed_lib_op_impls_UnaryOpImpl = UnaryOpImpl()
        self.adapter_testfed_lib_op_impls_BinaryOpImpl = BinaryOpImpl()

    async def call_ops_NullaryOp(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_NullaryOpImpl.body()

    async def call_ops_NullaryOpTuple(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_NullaryOpTupleImpl.body()

    async def call_ops_BinaryOp(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_BinaryOpImpl.body(**kwargs)

    async def call_ops_UnaryOp(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_UnaryOpImpl.body(**kwargs)

    async def discover_ops_NullaryOp(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_NullaryOpImpl
        )

    async def discover_ops_NullaryOpTuple(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_NullaryOpTupleImpl
        )

    async def discover_ops_UnaryOp(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_UnaryOpImpl, **kwargs
        )

    async def discover_ops_BinaryOp(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_BinaryOpImpl, **kwargs
        )


class ThisSite(nv_dfm_core.exec.Site):
    def __init__(self, dfm_context: nv_dfm_core.exec.DfmContext):
        super().__init__(
            dfm_context=dfm_context,
            cache_config=FsspecConfig(
                protocol="file", storage_options={}, base_path=None
            ),
            secrets_vault_config=SecretsVaultConfig(path=None, args={}),
        )
        # providers
        self.provider1 = provider1(self)
        # adapters
        self.adapter_testfed_lib_op_impls_NullaryOpImpl = NullaryOpImpl()
        self.adapter_testfed_lib_op_impls_NullaryOpTupleImpl = NullaryOpTupleImpl()
        self.adapter_testfed_lib_op_impls_UnaryOpImpl = UnaryOpImpl()
        self.adapter_testfed_lib_op_impls_BinaryOpImpl = BinaryOpImpl()

    async def call_ops_NullaryOp(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_NullaryOpImpl.body()

    async def call_ops_NullaryOpTuple(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_NullaryOpTupleImpl.body()

    async def call_ops_BinaryOp(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_BinaryOpImpl.body(**kwargs)

    async def call_ops_UnaryOp(self, **kwargs):
        return await self.adapter_testfed_lib_op_impls_UnaryOpImpl.body(**kwargs)

    async def discover_ops_NullaryOp(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_NullaryOpImpl
        )

    async def discover_ops_NullaryOpTuple(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_NullaryOpTupleImpl
        )

    async def discover_ops_UnaryOp(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_UnaryOpImpl, **kwargs
        )

    async def discover_ops_BinaryOp(self, **kwargs):
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(
            adapter=self.adapter_testfed_lib_op_impls_BinaryOpImpl, **kwargs
        )
