# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal

from ...api.tasks import GenerateReport as GenerateReport_1
from ...api.tasks import ProcessData as ProcessData_1
from ...api.tasks import RunComputation as RunComputation_1
from ...api.tasks import RunController as RunController_1


class ProcessData(ProcessData_1):
    """
    Processes the input data
    """

    site: Literal['worker'] = 'worker'
    provider: None = None
    dfm_class_name: Literal['testpkg.fed.site.worker.tasks.ProcessData'] = (
        'testpkg.fed.site.worker.tasks.ProcessData'
    )
    __api_name__: Literal['tasks.ProcessData'] = 'tasks.ProcessData'


class RunComputation(RunComputation_1):
    """
    Runs the computation
    """

    site: Literal['worker'] = 'worker'
    provider: None = None
    dfm_class_name: Literal['testpkg.fed.site.worker.tasks.RunComputation'] = (
        'testpkg.fed.site.worker.tasks.RunComputation'
    )
    __api_name__: Literal['tasks.RunComputation'] = 'tasks.RunComputation'


class RunController(RunController_1):
    """
    Runs the controller
    """

    site: Literal['worker'] = 'worker'
    provider: None = None
    dfm_class_name: Literal['testpkg.fed.site.worker.tasks.RunController'] = (
        'testpkg.fed.site.worker.tasks.RunController'
    )
    __api_name__: Literal['tasks.RunController'] = 'tasks.RunController'


class GenerateReport(GenerateReport_1):
    """
    Generates the report
    """

    site: Literal['worker'] = 'worker'
    provider: None = None
    dfm_class_name: Literal['testpkg.fed.site.worker.tasks.GenerateReport'] = (
        'testpkg.fed.site.worker.tasks.GenerateReport'
    )
    __api_name__: Literal['tasks.GenerateReport'] = 'tasks.GenerateReport'
