# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

import inspect

import nv_dfm_core.exec
import nv_dfm_core.exec.discovery
import nv_dfm_core.telemetry
from nv_dfm_core.exec import FsspecConfig, SecretsVaultConfig
import examplefed.lib.customer_service


class ThisSite(nv_dfm_core.exec.Site):
    def __init__(self, dfm_context: nv_dfm_core.exec.DfmContext):
        super().__init__(
            dfm_context=dfm_context,
            cache_config=FsspecConfig(protocol='file', storage_options={}, base_path=None),
            secrets_vault_config=SecretsVaultConfig(path=None, args={})
        )
        # providers
        # adapters
        _adapter_params = inspect.signature(examplefed.lib.customer_service.GreetMe).parameters
        _adapter_kwargs = {}
        if 'site' in _adapter_params:
            _adapter_kwargs['site'] = self
        if 'provider' in _adapter_params:
            _adapter_kwargs['provider'] = None
        self.adapter_examplefed_lib_customer_service_GreetMe = examplefed.lib.customer_service.GreetMe(**_adapter_kwargs)
    
    async def call_users_GreetMe(self, **kwargs):
        # prepare arguments
        name = kwargs.get("name", None)
        greet_fmt = "Hello from the local app, {name}! How are you?"
        # handle exposed args (if any)
        greet_fmt = kwargs.get("greeting", None) or greet_fmt
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "name": name,
           "greet_fmt": greet_fmt,
        }
        # call adapter with telemetry
        with nv_dfm_core.telemetry.adapter_span(self.dfm_context, "GreetMe", "users.GreetMe") as _dfm_span_:
            _dfm_result_ = await self.adapter_examplefed_lib_customer_service_GreetMe.body(**_dfm_prepped_kwargs_)
            if _dfm_span_:
                _dfm_span_.set_ok()
            return _dfm_result_

    async def discover_users_GreetMe(self, **kwargs):
        # prepare arguments
        name = kwargs.get("name", None)
        greet_fmt = "Hello from the local app, {name}! How are you?"
        # handle exposed args (if any)
        greet_fmt = kwargs.get("greeting", None) or greet_fmt
        # assemble into a dict
        _dfm_prepped_kwargs_ = {
           "name": name,
           "greet_fmt": greet_fmt,
        }
        return await nv_dfm_core.exec.discovery.AdviceBuilder.build_advice(adapter=self.adapter_examplefed_lib_customer_service_GreetMe, **_dfm_prepped_kwargs_)

    