# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

import logging
from typing import Any, Literal, Optional
from nv_dfm_core.session import Session
from pathlib import Path

from ._this_site import ThisSite

API_VERSION: Literal['0.0.1'] = '0.0.1'

def get_session(
    target: Literal['flare', 'local'] = 'flare',
    logger: logging.Logger | None = None,
    **kwargs: Any
) -> Session:
    return Session(
        federation_name='examplefed',
        homesite='reception',
        target=target,
        logger=logger,
        **kwargs,
    )

__all__ = ["ThisSite", "get_session", "API_VERSION"]