# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal, Union

from nv_dfm_core.api import Advise, NodeParam, PlaceParam

from ...api.users import GreetMe as GreetMe_1


class GreetMe(GreetMe_1):
    """
    Runs the standard greeting operation on the local site

    Parameters:
        greeting: [Accepts: literal input, node input, place input. Discoverable]
            In the local concierge site, a user can override the default greeting using a format string like 'Hello from {name}!'
    """

    class Config:
        arbitrary_types_allowed = True

    site: Literal['concierge'] = 'concierge'
    provider: None = None
    dfm_class_name: Literal['examplefed.fed.site.concierge.users.GreetMe'] = (
        'examplefed.fed.site.concierge.users.GreetMe'
    )
    __api_name__: Literal['users.GreetMe'] = 'users.GreetMe'
    greeting: Union[str, NodeParam, PlaceParam, Advise] = None
