# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

operation:
  xarray.RenderUint8ToImages:
    description: "Renders the uint8 to images"
    parameters:
      data:
        description: "The xarray to render"
        type: object
      variable:
        description: "The variable to render"
        type: string
      xydims:
        description: "The names of the x and y dimensions"
        type: array
      time_dimension:
        description: "The name of the time dimension"
        type: string
      additional_meta_data:
        description: "Additional metadata to add to the texture file (JSON string)"
        type: object
      return_meta_data:
        description: "Whether to return the metadata"
        type: boolean
      return_image_data:
        description: "Whether to return the image data"
        type: boolean
      quality:
        description: "The quality of the image"
        type: number
      format:
        description: "The format of the image"
        type: string
    required:
      - data
      - variable
      - xydims
      - time_dimension
    returns: object
interface:
  "#/operations/xarray.RenderUint8ToImages":
    adapter: nv_dfm_lib_weather.xarray.RenderUint8ToImages
    description: "Renders the uint8 to images"
    is-async: true
    args:
      data:
        from-param: data
      variable:
        from-param: variable
      xydims:
        from-param: xydims
      time_dimension:
        from-param: time_dimension
      additional_meta_data:
        from-param: additional_meta_data
      format:
        from-param: format
      return_meta_data:
        from-param: return_meta_data
      return_image_data:
        from-param: return_image_data
