# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
from datetime import datetime

import numpy as np
import torch
import xarray
from earth2studio.data import CBottle3D
from earth2studio.lexicon.cbottle import CBottleLexicon

from nv_dfm_core.exec import Provider
from nv_dfm_core.exec.discovery import (
    AdvisedDict,
    AdvisedOneOf,
    AdvisedSubsetOf,
    field_advisor,
)

from ..site import ModelCacheSite
from ..utils._device_utils import available_devices, setup_device


class CbottleDataGen:
    """
    CBottle3D synthetic climate data generator.

    This class provides functionality to generate synthetic climate data using the
    CBottle3D diffusion model. It supports generating multiple climate variables at
    specified timestamps with customizable sampling parameters.

    The generated data can be returned either on a lat/lon grid or a nested HealPix grid,
    making it suitable for various climate modeling and analysis applications.

    Attributes:
        _site: Model cache site for managing model storage and retrieval
        _provider: DFM provider instance for the service
        _logger: Logger instance for tracking operations and debugging
    """

    def __init__(self, site: ModelCacheSite, provider: Provider | None):
        """
        Initialize the CBottle data generator.

        Args:
            site: ModelCacheSite instance for model caching and management
            provider: DFM Provider instance, or None if running standalone
        """
        self._site: ModelCacheSite = site
        self._provider = provider
        self._logger = site.dfm_context.logger

    @field_advisor("variables")
    async def available_variables(self, _value, _context):
        """
        Field advisor that provides available climate variables for the CBottle model.

        This method is used by the DFM discovery system to inform clients about which
        climate variables can be generated by the CBottle3D model. The available variables
        are defined by the CBottle lexicon vocabulary.

        Args:
            _value: The current value (unused)
            _context: The discovery context (unused)

        Returns:
            AdvisedSubsetOf: A set of valid variable names that can be selected from
        """
        self._logger.info("Discovery started for variables")
        result = AdvisedSubsetOf(CBottleLexicon.VOCAB.keys())  # type: ignore
        self._logger.info(f"Discovery finished for variables: {result}")
        return result

    @field_advisor("time")
    async def valid_time(self, _value, _context):
        """
        Field advisor that provides the valid time range for CBottle data generation.

        This method informs clients about the temporal range supported by the CBottle3D
        model. The time range represents the period for which the model can generate
        synthetic climate data.

        Args:
            _value: The current value (unused)
            _context: The discovery context (unused)

        Returns:
            AdvisedDict: Dictionary containing first_date and last_date constraints
        """
        dict_advice = AdvisedDict(
            {
                "first_date": "1970-01-01T00:00:00",
                "last_date": "2022-12-31T00:00:00",
            },
            allow_extras=True,
        )
        return dict_advice

    @field_advisor("device")
    async def valid_device(self, _value, _context):
        """
        Field advisor that provides available compute devices for model inference.

        This method queries the system for available compute devices (CPU and CUDA GPUs)
        and informs clients about which devices can be used for running the CBottle3D model.

        Args:
            _value: The current value (unused)
            _context: The discovery context (unused)

        Returns:
            AdvisedOneOf: A list of valid device identifiers (e.g., "cpu", "cuda", "cuda:0")
        """
        return AdvisedOneOf(available_devices())

    async def body(
        self,
        variables: list[str],
        time: str,
        n_samples: int = 1,
        seed: int | None = None,
        device: str | None = None,
        lat_lon: bool = True,
    ) -> xarray.Dataset:
        """
        Generate synthetic climate data using the CBottle3D diffusion model.

        This method uses the CBottle3D generative model to create synthetic climate data
        for specified variables and timestamps. The model employs diffusion-based generation
        to produce physically plausible climate fields that can be used for analysis,
        testing, or data augmentation.

        The generated data is cached using the model cache system to optimize performance
        across multiple requests with the same parameters.

        Args:
            variables: List of climate variables to generate. Must be valid CBottle lexicon
                      variables (e.g., ["msl", "tcwv", "u10m", "v10m"]). Use the
                      available_variables field advisor to discover valid options.
            time: Timestamp string in ISO 8601 format (e.g., "2022-09-05T00:00:00" or
                 "2022-09-05T00:00:00Z"). The timestamp must fall within the valid range
                 specified by the valid_time field advisor.
            n_samples: Number of independent samples to generate for the given timestamp.
                      Each sample represents a different realization from the generative model.
                      (default: 1)
            seed: Random seed for reproducibility. (default: None)
            device: Compute device to use for model inference. Options:
                   - "cuda" or "cuda:0": Use default CUDA device (requires GPU)
                   - "cuda:N": Use specific CUDA device N (e.g., "cuda:1" for second GPU)
                   - "cpu": Force CPU usage (slower but doesn't require GPU)
                   - None: Auto-select (CUDA if available, CPU otherwise)
                   Use the valid_device field advisor to discover available options.
                   (default: None)
            lat_lon: Whether to return data on a regular lat/lon grid (True) or a nested
                    HealPix grid (False). Most use cases should use lat/lon format.
                    (default: True)

        Returns:
            xarray.Dataset: Generated synthetic climate data set.

        Raises:
            ValueError: If variables list is empty, contains invalid variable names,
                       or if the timestamp format is invalid.
            RuntimeError: If model loading or inference fails.

        Example:
            >>> result = await data_gen.body(
            ...     variables=["msl", "tcwv"],
            ...     time="2022-09-05T00:00:00",
            ...     n_samples=5,
            ...     seed=42,
            ...     device="cuda:0"
            ... )
        """
        cbottle_ds_model = None
        try:
            # Validate that at least one variable is requested
            if not variables:
                raise ValueError("At least one variable must be specified")

            # Validate all requested variables exist in the CBottle lexicon vocabulary
            vocab = CBottleLexicon.VOCAB
            missing = set(variables) - set(vocab.keys())
            if missing:
                raise ValueError(
                    f"Invalid variable: {missing}. Valid variables: {vocab.keys()}"
                )

            # Parse timestamp string to datetime object, handling both standard and UTC formats
            if isinstance(time, str):
                timestamp = datetime.fromisoformat(time.replace("Z", "+00:00"))
            else:
                timestamp = time

            self._logger.info(
                f"Generating CBottle data for variables: {variables}, timestamp: {timestamp}, samples: {n_samples}"
            )

            # Set random seed for reproducibility if provided
            # This ensures deterministic generation across runs with the same seed
            if seed is not None:
                torch.manual_seed(seed=seed)
                if torch.cuda.is_available():
                    torch.cuda.manual_seed(seed)

            # Determine the target device (CPU or CUDA) based on availability and user preference
            local_device = setup_device(device, self._logger)

            # Define model loader function for the cache system
            # This function is called only if the model is not already cached
            def _loader():
                package = CBottle3D.load_default_package()
                return CBottle3D.load_model(package, seed=seed, lat_lon=lat_lon)

            # Load the CBottle3D model from cache or initialize it if not cached
            # The cache key includes lat_lon and seed to ensure proper model configuration
            cache = self._site.model_cache
            cbottle_ds_model = cache.get_or_load(
                model_id=f"cbottle.data_gen:latlon={bool(lat_lon)}:seed={seed}",
                loader=_loader,
                device=str(local_device),
            )
            self._logger.info(
                f"CBottle3D model loaded and moved to device: {local_device}"
            )

            # Create a list of timestamps for the requested number of samples
            # Each sample uses the same timestamp but produces a different realization
            timestamps = [timestamp for _ in range(n_samples)]

            # Generate synthetic climate data using the CBottle3D model
            # This is a synchronous CPU/GPU-intensive operation, so we run it in a thread
            # to avoid blocking the async event loop
            def generate_cbottle_data():
                return cbottle_ds_model(timestamps, variables)

            cbottle_da = await asyncio.to_thread(generate_cbottle_data)

            # Convert the DataArray to a Dataset, preserving each variable as a separate data variable
            # This structure makes it easier to work with individual climate variables
            cbottle_ds_full = cbottle_da.to_dataset(dim="variable")

            # Ensure the time coordinate uses numpy's datetime64 format for consistency
            # This is important for downstream processing and compatibility with other tools
            if "time" in cbottle_ds_full.coords:
                if not np.issubdtype(
                    cbottle_ds_full.coords["time"].dtype, np.datetime64
                ):
                    cbottle_ds_full.coords["time"] = cbottle_ds_full.coords[
                        "time"
                    ].astype("datetime64[ns]")

            return cbottle_ds_full
        except Exception as e:
            self._logger.error(f"Error generating CBottle data: {e}")
            raise e
