# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal, Union

from nv_dfm_core.api import Advise, NodeParam, Operation, PlaceParam


class NullaryOp(Operation):
    """
    Parameters:
        -

    Returns: string
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal["tests.assets.testfed.fed.api.ops.NullaryOp"] = (
        "tests.assets.testfed.fed.api.ops.NullaryOp"
    )
    __api_name__: Literal["ops.NullaryOp"] = "ops.NullaryOp"


class NullaryOpTuple(Operation):
    """
    Parameters:
        -

    Returns: (string, string)
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal["tests.assets.testfed.fed.api.ops.NullaryOpTuple"] = (
        "tests.assets.testfed.fed.api.ops.NullaryOpTuple"
    )
    __api_name__: Literal["ops.NullaryOpTuple"] = "ops.NullaryOpTuple"


class UnaryOp(Operation):
    """
    Parameters:
        p1: [Accepts: literal input, node input, place input. Discoverable]

    Returns: string
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal["tests.assets.testfed.fed.api.ops.UnaryOp"] = (
        "tests.assets.testfed.fed.api.ops.UnaryOp"
    )
    __api_name__: Literal["ops.UnaryOp"] = "ops.UnaryOp"
    p1: Union[str, dict[str, str], NodeParam, PlaceParam, Advise]


class OpWithDefault(Operation):
    """
    Parameters:
        p1: [Accepts: literal input, node input, place input. Discoverable]

    Returns: string
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal["tests.assets.testfed.fed.api.ops.OpWithDefault"] = (
        "tests.assets.testfed.fed.api.ops.OpWithDefault"
    )
    __api_name__: Literal["ops.OpWithDefault"] = "ops.OpWithDefault"
    p1: Union[str, NodeParam, PlaceParam, Advise] = "api-default"


class BinaryOp(Operation):
    """
    Parameters:
        p1: [Accepts: literal input, node input, place input. Discoverable]
        p2: [Accepts: literal input, node input, place input. Discoverable]

    Returns: string
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal["tests.assets.testfed.fed.api.ops.BinaryOp"] = (
        "tests.assets.testfed.fed.api.ops.BinaryOp"
    )
    __api_name__: Literal["ops.BinaryOp"] = "ops.BinaryOp"
    p1: Union[str, NodeParam, PlaceParam, Advise]
    p2: Union[str, NodeParam, PlaceParam, Advise]
